server:
  port: 8870

signing: 
  key: 345345fsdfsf5345

# ORACLE #    
spring:
 datasource:
  url: jdbc:oracle:thin:@localhost:1521:xe
  username: GALAXY_DEV
  password: 123456
  driver-class-name: oracle.jdbc.driver.OracleDriver
  
# Actuator
management:
  endpoints:
   web:
     exposure:
       include: "*"
  endpoint:
   health:
     show-details: always
  metrics:
   tags:
     application: ms-admin-autorization

#JAEGER
opentracing:
  jaeger:
    const-sampler:
      decision: true
    enabled: true
    log-spans: true
    service-name: ms-admin-autorization
    udp-sender:
      host: localhost
      port: 6831